app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, SelectField, TextAreaField
from wtforms.validators import DataRequired, Length, ValidationError

entries = [('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Transport', 'Transport'),
           ('Services', 'Services'), ('Clothes', 'Clothes'), ('Household', 'Household'),
           ('Medicines', 'Medicines'), ('Credit', 'Credit'), ('Technique', 'Technique'),
           ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Other', 'Other')]
kind_choice = [(0, 'Expenses'), (1, 'Income')]


class CreateCardForm(FlaskForm):
    price = StringField('Price', validators=[DataRequired()])
    category = SelectField('Category', choices=entries, validators=[DataRequired()])
    kind = SelectField(choices=kind_choice, coerce=int)#, validators=[DataRequired()])
    note = TextAreaField('Note', validators=[Length(max=32)])
    submit = SubmitField('Create')

    def validate_price(self, price):
        try:
            float(price.data)
        except ValidationError:
            raise ValidationError('Price must be float')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import calendar
from datetime import datetime
from app.main import bp
from app.request_db import CardResponse
from app.crendentials import *
from app.models import Card
from flask import render_template, request, current_app
from flask_login import login_required, current_user


@bp.route('/')
def preview():
    return render_template('main/preview.html')


@bp.route('/index', methods=['GET'])
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    month = request.args.get('month', datetime.utcnow().month, type=int)
    year = request.args.get('year', datetime.utcnow().year, type=int)

    if month < 1:
        month = 12
        year = year - 1
    elif month > 12:
        month = 1
        year = year + 1

    cards = Card.query.filter_by(
        payer=current_user,
        month=month,
        year=year
    ).order_by(Card.timestamp.desc()).paginate(
        page=page,
        per_page=current_app.config['CARDS_PER_PAGE'],
        error_out=False)

    date = [calendar.month_name[month], str(year)]

    # statistics
    response = CardResponse(current_user, month=month, year=year)
    categories, prices = response.get_cards('category')
    percents = get_percents(categories, prices)

    # pie
    colors = ['#0260E8', '#64C7FF', '#004156', '#41B619', '#F5E027', '#FB9F82',
              '#FF6B00', '#FFDFDC', '#B40A1B', '#DC3790', '#A400FF', '#58595B']
    bg_colors = colors[:len(categories)]

    all_cards = Card.query.filter_by(payer=current_user,
                                     month=month,
                                     year=year).all()
    total = get_total(all_cards)
    return render_template('main/index.html', cards=cards,
                           date=date, categories=categories, prices=prices, bg_colors=bg_colors, page=page,
                           total=total, percents=percents, month=month, year=year)


@bp.route('/table', methods=['GET', 'POST'])
@login_required
def table():
    cards = current_user.notes.all()
    return render_template('main/table.html', cards=cards)


@bp.route('/describe', methods=['GET'])
@login_required
def describe():
    month = request.args.get('month', type=int)
    year = request.args.get('year', type=int)
    category = request.args.get('category', type=str)

    date = [calendar.month_name[month], str(year)]

    response = CardResponse(current_user)
    months, prices_months = response.get_expenses_month(year=year, category=category)
    months = calendar_month(months)

    response = CardResponse(current_user, month=month)
    categories, prices_category = response.get_cards('category')

    try:
        idx = categories.index(category)
        target = categories.pop(idx)
        price = prices_category.pop(idx)
        categories = [target, 'Other']
        prices_category = [price, sum(prices_category)]
    except:
        categories = ['Other']
        prices_category = [sum(prices_category)]

    response = CardResponse(current_user, category=category, month=month)
    days, prices_days = response.get_cards('day')

    return render_template('main/stat_expenses.html',
                           date=date, months=months, prices_months=prices_months,
                           categories=categories, prices_category=prices_category,
                           days=days, prices_days=prices_days,
                           month=month, year=year, category=category)


@bp.route('/get_data', methods=['GET'])
@login_required
def get_data():
    _page = request.args.get('page', 1, type=int)
    month = request.args.get('month', type=int)
    year = request.args.get('year', type=int)
    cards = Card.query.filter_by(
        payer=current_user,
        month=month,
        year=year
    ).order_by(Card.timestamp.desc()).paginate(
        page=_page,
        per_page=current_app.config['CARDS_PER_PAGE'],
        error_out=False)
    next_url_page = cards.next_num if cards.has_next else None
    prev_url_page = cards.prev_num if cards.has_prev else None
    all_cards = Card.query.filter_by(payer=current_user,
                                     month=month,
                                     year=year).all()
    total = get_total(all_cards)
    return render_template('include/_card.html', cards=cards, _page=_page,
                           ajax_next_url=next_url_page, ajax_prev_url=prev_url_page,
                           total=total)

app/templates/main/base.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Bookkeeping</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
              integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
              integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
        <script type=text/javascript src="{{ url_for('static', filename='js/jquery-3.4.1.min.js') }}"></script>
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark position-fixed w-100" style="height: 80px; background-color: #2a2a2a; top: 0; z-index: 30;">
            <a class="navbar-brand" href="{{ url_for('main.preview') }}"><b>Bookkeeping</b></a>
            <div class="collapse navbar-collapse justify-content-end">
                <ul class="navbar-nav">
                    <li class="mx-4 decor-left"><a class="nav-link" href="{{ url_for('main.index')}}">Home</a></li>
                    {% if current_user.is_active %}
                    <li class="mx-4 decor-left"><a href="{{ url_for('auth.logout') }}"><button class="light-button">Log out</button></a></li>
                    {% else %}
                    <li class="mx-4 decor-left"><a class="nav-link" href="{{ url_for('auth.login') }}">Sign in</a></li>
                    <li class="mx-4 decor-left"><a class="nav-link" href="{{ url_for('auth.register') }}">Sign up</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% if current_user.is_active %}
        <div class="burger-menu">
            <a href="" class="burger-menu__button"><span class="burger-menu__lines"></span></a>
            <nav class="burger-menu__nav">
                <a href="#" class="burger-menu__link">{{ current_user.username }}</a>
                <a href="{{ url_for('main.index') }}" class="burger-menu__link">Home</a>
                <a href="{{ url_for('card.create') }}" class="burger-menu__link">Add card</a>
                <a href="{{ url_for('main.table') }}" class="burger-menu__link">Table</a>
            </nav>
        </div>
        {% endif %}
        <div class="d-flex flex-column flex-grow-1" style="margin-top: 140px;margin-bottom: 60px">
            <div class="container">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert alert-info" style="z-index: 100" role="alert">{{ message }}!</div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {% block app_content %}{% endblock %}
            </div>
        </div>
        <footer  style="background-color: #2a2a2a;">
            <div class="container py-2" style="color:#b9b9b9;">
                <div class="d-flex justify-content-between">
                    <span>&copy; Copyright 2019. All rights reserved.</span>
                    <span>Created by <span style="color: #ffffff;">Denis Pashnev</span> <a href="https://github.com/MickiMouse/bookkeeping"><i class="fab fa-github" style="color: #FFFFFF;"></i></a></span>
                </div>
            </div>
        </footer>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"
                integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='js/burger.js') }}"></script>
        {% block scripts %}{% endblock %}
    </body>
</html>

app/templates/main/index.html
{% extends 'main/base.html' %}


{% block app_content %}
    <div class="d-flex justify-content-between">
        <div class="d-flex">
            <a href="{{ url_for('main.index', month=month - 1, year=year) }}" class="btn-lg">&lt;</a>
            <h2>{{ date[0] }} {{ date[1] }}</h2>
            <a href="{{ url_for('main.index', month=month + 1, year=year) }}" class="btn-lg">&gt;</a>
        </div>
        <a href="{{ url_for('card.create') }}"><button class="light-button">Add card</button></a>
    </div>
    {% if prices %}
    <div class="d-flex my-3" id="content">
        {% include 'include/_card.html' %}
    </div>
    <div class="d-flex">
        <div class="flex-column flex-grow-1 bg-white mr-2">
            <p class="p-2 my-0">Top-5 expensive categories in {{ date[0] }} {{ date[1] }}</p>
            <table class="table">
            {% for percent in percents %}
                <tr>
                    <td class="percent">
                        <span class="decor-left">
                            <a href="{{ url_for('main.describe', category=percent[0], year=year, month=month) }}">
                                {{ percent[0] }}
                            </a>
                        </span>
                    </td>
                    <td class="percent"><span>{{ percent[1] }}</span></td>
                    <td class="percent"><span class="float-right">{{ percent[2] }}%</span></td>
                </tr>
            {% endfor %}
            </table>
        </div>
        <div class="flex-column flex-grow-1 bg-white ml-2" style="max-width: 550px;">
            <p class="p-2 my-0   border-bottom">Costs per {{ date[0] }} {{ date[1] }}</p>
            <canvas id="pieAllCategories"></canvas>
        </div>
    </div>
    {% else %}
        <div class="d-flex justify-content-center mt-5">
            <h2>No records for this month.</h2>
        </div>
    {% endif %}
{% endblock %}


{% block scripts %}
    <script>
        let categories = {{ categories|safe }};
        let prices = {{ prices|safe }}
        new Chart(document.getElementById("pieAllCategories").getContext('2d'), {
            type: 'doughnut',
            data: {
                labels: categories,
                datasets: [{
                    backgroundColor: {{ bg_colors|safe }},
                    data: prices,
                }]
            },
            options: {
                legend: {
                    display: true,
                    position: 'left'
                }
            }
        });
        function get_data(page) {
            $.ajax({
                type: "GET",
                url: "/get_data?month={{ month }}&year={{ year }}&page="+page,
                success: function (response) {
                    $('#content').html(response);
                },
                error: function (error) {
                    console.log(error);
                }
            });
        }
        get_data('{{ page }}');
    </script>
{% endblock %}

app/templates/main/preview.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Bookkeeping</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
              integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    </head>
    <body class="bg-img d-flex justify-content-center">
        <a class="mx-5" href="{% if current_user.is_authenticated %}{{ url_for('main.index') }}{% else %}{{ url_for('auth.register') }}{% endif %}">
            <button class="light-button"><span class="h1">Get Started</span></button>
        </a>
    </body>
</html>

app/templates/main/stat_expenses.html
{% extends 'main/base.html' %}


{% block app_content %}
    <div class="d-flex flex-column">
        <div class="d-flex flex-row">
            <div class="flex-column flex-grow-1 bg-white mr-2">
                <h3 class="p-2 border-bottom">{{ category }}</h3>
                <canvas id="chartBar"></canvas>
            </div>
            <div class="flex-column flex-grow-1 bg-white ml-2">
{#            <a href="{{ url_for('main.describe', category=category, year=year, month=month-1) }}">LEFT</a>#}
                <h3 class="p-2 border-bottom">{{ date[0] }} {{ date[1] }}</h3>
{#            <a href="{{ url_for('main.describe', category=category, year=year, month=month+1) }}">RIGHT</a>#}
                <canvas id="chartPie"></canvas>
            </div>
        </div>
        <div class="flex-column bg-white mt-3">
            <h3 class="p-2 border-bottom">{{ date[0] }} {{ date[1] }}</h3>
            <canvas id="chartLine"></canvas>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        let months = {{ months|safe }};
        let prices = {{ prices_months|safe }};
        let bar = document.getElementById('chartBar').getContext('2d');
        new Chart(bar, {
            type: 'horizontalBar',
            data: {
                labels: months,
                datasets: [{
                    label: '{{ category }}',
                    data: prices,
                    fill: false,
                    backgroundColor: 'rgba(42,39,255,0.79)',
                    borderColor: 'rgba(42,39,255,0.79)',
                    borderWidth: 2,
                    hoverBackgroundColor: 'rgba(42,39,255,0.79)',
                    hoverBorderColor: 'rgba(42,39,255,0.79)',
                    lineTension: 0.1,
                    pointHitRadius: 5,
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: "black"
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: "black"
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: "black",
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        let categories = {{ categories|safe }};
        let prices_cat = {{ prices_category|safe }};
        let pie = document.getElementById('chartPie').getContext('2d');
        new Chart(pie, {
            type: 'pie',
            data: {
                labels: categories,
                datasets: [{
                    data: prices_cat,
                    backgroundColor: ['rgba(42,39,255,0.79)'],
                }]
            },
            options: {
                legend: {
                    display: true,
                    position: 'left'
                }
            }
        });

        let days = {{ days|safe }};
        let prices_days = {{ prices_days|safe }};
        let line = document.getElementById('chartLine').getContext('2d');
        new Chart(line, {
            type: 'line',
            data: {
                labels: days,
                datasets: [{
                    label: '{{ category }}',
                    data: prices_days,
                    borderColor: 'rgba(42,39,255,0.79)',
                    backgroundColor: 'rgba(42,39,255,0.69)'
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: 'black'
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: 'black',
                            beginAtZero: true
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: 'black'
                        }
                    }]
                }
            }
        })
    </script>
{% endblock %}

app/templates/main/statistics.html
{% extends 'main/base.html' %}


{% block app_content %}
    <div class="d-flex flex-column">
        <div class="d-flex flex-row">
            <div class="flex-column flex-grow-1 bg-white mr-2">
                <h3 class="p-2 border-bottom">{{ category }}</h3>
                <canvas id="chartBar"></canvas>
            </div>
            <div class="flex-column flex-grow-1 bg-white ml-2">
{#            <a href="{{ url_for('main.describe', category=category, year=year, month=month-1) }}">LEFT</a>#}
                <h3 class="p-2 border-bottom">{{ date[0] }} {{ date[1] }}</h3>
{#            <a href="{{ url_for('main.describe', category=category, year=year, month=month+1) }}">RIGHT</a>#}
                <canvas id="chartPie"></canvas>
            </div>
        </div>
        <div class="flex-column bg-white mt-3">
            <h3 class="p-2 border-bottom">{{ date[0] }} {{ date[1] }}</h3>
            <canvas id="chartLine"></canvas>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        let months = {{ months|safe }};
        let prices = {{ prices_months|safe }};
        let bar = document.getElementById('chartBar').getContext('2d');
        new Chart(bar, {
            type: 'horizontalBar',
            data: {
                labels: months,
                datasets: [{
                    label: '{{ category }}',
                    data: prices,
                    fill: false,
                    backgroundColor: 'rgba(42,39,255,0.79)',
                    borderColor: 'rgba(42,39,255,0.79)',
                    borderWidth: 2,
                    hoverBackgroundColor: 'rgba(42,39,255,0.79)',
                    hoverBorderColor: 'rgba(42,39,255,0.79)',
                    lineTension: 0.1,
                    pointHitRadius: 5,
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: "black"
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: "black"
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: "black",
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        let categories = {{ categories|safe }};
        let prices_cat = {{ prices_category|safe }};
        let pie = document.getElementById('chartPie').getContext('2d');
        new Chart(pie, {
            type: 'pie',
            data: {
                labels: categories,
                datasets: [{
                    data: prices_cat,
                    backgroundColor: ['rgba(42,39,255,0.79)'],
                }]
            },
            options: {
                legend: {
                    display: true,
                    position: 'left'
                }
            }
        });

        let days = {{ days|safe }};
        let prices_days = {{ prices_days|safe }};
        let line = document.getElementById('chartLine').getContext('2d');
        new Chart(line, {
            type: 'line',
            data: {
                labels: days,
                datasets: [{
                    label: '{{ category }}',
                    data: prices_days,
                    borderColor: 'rgba(42,39,255,0.79)',
                    backgroundColor: 'rgba(42,39,255,0.69)'
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: 'black'
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: 'black',
                            beginAtZero: true
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: 'black'
                        }
                    }]
                }
            }
        })
    </script>
{% endblock %}

app/templates/main/table.html
{% extends 'main/base.html' %}


{% block app_content %}
    <table class="table table-bordered table-light">
        <tr>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col">Year</th>
            <th scope="col">Month</th>
            <th scope="col">Day</th>
        </tr>
        {% for card in cards %}
            <tr>
                <td>{{ card.category }}</td>
                <td>
                    {% if card.kind %}
                        <span class="badge badge-pill badge-success">+{{ card.price }}</span>
                    {% else %}
                        <span class="badge badge-pill badge-danger">-{{ card.price }}</span>
                    {% endif %}
                <td>{{ card.year }}</td>
                <td>{{ card.month }}</td>
                <td>{{ card.day }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}