app/card/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, SelectField, TextAreaField, FloatField, IntegerField
from wtforms.validators import DataRequired, Length, Optional, NumberRange, ValidationError

expenses = [('Housing', 'Housing'), ('Utilities', 'Utilities'), ('Food', 'Food'), ('Transport', 'Transport'),
            ('Services', 'Services'), ('Clothes', 'Clothes'), ('Household', 'Household'),
            ('Medicines', 'Medicines'), ('Credit', 'Credit'), ('Technique', 'Technique'),
            ('Entertainment', 'Entertainment'), ('Education', 'Education'), ('Other expenses', 'Other expenses')]
incomes = [('Business', 'Business'), ('Work', 'Work'), ('Other incomes', 'Other incomes')]
kind_choice = [(0, 'Expenses'), (1, 'Income')]


class CardForm(FlaskForm):
    price = FloatField('Price', validators=[DataRequired()])
    category_expenses = SelectField('Category expenses', choices=expenses, coerce=str, validators=[Optional()])
    category_incomes = SelectField('Category incomes', choices=incomes, coerce=str, validators=[Optional()])
    kind = SelectField(choices=kind_choice, coerce=int)
    day = IntegerField(validators=[NumberRange(min=1, max=31)])
    month = IntegerField(validators=[NumberRange(min=1, max=12)])
    year = IntegerField(validators=[NumberRange(min=1970)])
    note = TextAreaField(validators=[Length(max=32)])
    submit = SubmitField('Create')

    def validate_price(self, price):
        try:
            float(price.data)
        except ValidationError:
            raise ValidationError('Price must be float')

app/card/__init__.py
from flask import Blueprint

bp = Blueprint('card', __name__)

from app.card import routes

app/card/routes.py
from datetime import datetime
from app import db
from app.card import bp
from app.card.forms import CardForm
from app.models import Card
from flask import request, redirect, url_for, render_template
from flask_login import login_required, current_user


@bp.route('/make_card', methods=['GET', 'POST'])
@login_required
def create():
    form = CardForm()
    if form.validate_on_submit():
        category = form.category_expenses.data if form.kind.data == 0 else form.category_incomes.data
        card = Card(price=form.price.data,
                    category=category,
                    note=form.note.data,
                    kind=bool(form.kind.data),
                    payer=current_user,
                    year=form.year.data,
                    month=form.month.data,
                    day=form.day.data)
        db.session.add(card)
        db.session.commit()
        return redirect(url_for('main.index'))
    elif request.method == 'GET':
        form.day.data = datetime.utcnow().date().day
        form.month.data = datetime.utcnow().date().month
        form.year.data = datetime.utcnow().date().year
    return render_template('card/create_card.html', form=form)


@bp.route('/change', methods=['GET', 'POST'])
@login_required
def change():
    id = request.args.get('id', type=int)
    card = Card.query.get(int(id))
    form = CardForm()
    if form.validate_on_submit():
        category = form.category_expenses.data if form.kind.data == 0 else form.category_incomes.data
        card.kind = form.kind.data
        card.price = form.price.data
        card.category = category
        card.day = form.day.data
        card.month = form.month.data
        card.year = form.year.data
        card.note = form.note.data
        db.session.commit()
        return redirect(url_for('main.index'))
    elif request.method == 'GET':
        form.kind.data = card.kind
        form.price.data = card.price
        form.category_expenses.data = card.category
        form.category_incomes.data = card.category
        form.day.data = card.day
        form.month.data = card.month
        form.year.data = card.year
        form.note.data = card.note
    return render_template('card/change_card.html', form=form)


@bp.route('/delete', methods=['GET', 'POST'])
@login_required
def delete():
    id = request.args.get('id', type=int)
    card = Card.query.get(int(id))
    db.session.delete(card)
    db.session.commit()
    return redirect(url_for('main.index'))

app/templates/_card.html
<tr>
    <td>
        <span class="decor-left">
            <a href="{{ url_for('main.describe', category=card.category, year=card.year, month=card.month) }}">
                {{ card.category }}
            </a>
        </span>
    </td>
    <td><span>{% if card.note %}{{ card.note }}{% endif %}</span></td>
    {% if card.kind %}
        <td><span class="f-right" style="color: #00af00;">+{{ card.price }} {{ currency }}</span></td>
    {% else %}
        <td>
            <span class="f-right" style="color: #eb0000;">-{{ card.price }} {{ currency }}</span>
        </td>
    {% endif %}
    <td class="border-left border-bottom">
        <span class="d-flex justify-content-around">
            <a href="{{ url_for('card.change', id=card.id) }}">&#128394;</a>
            <a href="{{ url_for('card.delete', id=card.id) }}">
                <i class="material-icons">delete</i>
            </a>
        </span>
    </td>
</tr>

app/templates/cat_per_month.html
{% extends 'base.html' %}


{% block app_content %}
    <canvas id="bars"></canvas>
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script>
        let month = {{ month|safe }};
        let price = {{ prices|safe }};
        let bar = document.getElementById('bars').getContext('2d');
        new Chart(bar, {
            type: 'horizontalBar',
            data: {
                labels: month,
                datasets: [{
                    label: '{{ category }}',
                    data: price,
                    fill: false,
                    backgroundColor: "rgba(255,82,2, 0.8)",
                    borderColor: "rgba(255,5,7,0.8)",
                    borderWidth: 2,
                    hoverBackgroundColor: "rgba(255,82,2,1)",
                    hoverBorderColor: "rgba(255,5,7,1)",
                    lineTension: 0.1
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: "black"
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: "black"
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: "black",
                            beginAtZero: true
                        }
                    }]
                }
            }
        });
    </script>
{% endblock %}

app/templates/change_card.html
{% extends 'base.html' %}


{% block app_content %}
    <div class="d-flex justify-content-center">
        <form method="post" class="style-form shadow p-3 rounded">
            <h2>Change card</h2>
            {{ form.hidden_tag() }}
            <div class="form-group" onclick="exchange()">
                {{ form.kind(class="form-control") }}
                {% for error in form.kind.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.price(class="form-control", placeholder='Price') }}
                {% for error in form.price.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col">
                        {{ form.category_expenses.label }}
                        {{ form.category_expenses(class="form-control") }}
                        {% for error in form.category_expenses.errors %}
                            <div class="invalid-feedback d-block">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="col">
                        {{ form.category_incomes.label }}
                        {{ form.category_incomes(class="form-control") }}
                        {% for error in form.category_incomes.errors %}
                            <div class="invalid-feedback d-block">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col">
                        {{ form.day(class='form-control', placeholder='day (optional)') }}
                        {% for error in form.day.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
                    </div>
                    <div class="col">
                        {{ form.month(class='form-control', placeholder='month (optional)') }}
                        {% for error in form.month.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
                    </div>
                    <div class="col">
                        {{ form.year(class='form-control', placeholder='year (optional)') }}
                        {% for error in form.year.errors %}
                            <div class="invalid-feedback d-block">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.note(class="form-control", placeholder='Note (optional)', maxlength="32") }}
            </div>
            {{ form.submit(class="dark-button w-100", value='Change') }}
        </form>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        function exchange() {
            let e = document.getElementById('kind');
            let exp = document.getElementById('category_expenses');
            let inc = document.getElementById('category_incomes');
            if (e.value === '0') {
                console.log(e.value);
                inc.style = 'border: 2px solid rgba(175,1,5,0.77)';
                exp.style = 'border: 2px solid rgba(41,175,25,0.77)';
            } else {
                console.log(e.value);
                exp.style = 'border: 2px solid rgba(175,1,5,0.77)';
                inc.style = 'border: 2px solid rgba(41,175,25,0.77)';
            }
        }
        exchange();
    </script>
{% endblock %}

app/templates/create_card.html
{% extends 'base.html' %}


{% block app_content %}
    <div class="d-flex justify-content-center">
        <form method="post" class="style-form shadow p-3 rounded">
            <h2>Add card</h2>
            {{ form.hidden_tag() }}
            <div class="form-group" onclick="exchange()">
                {{ form.kind(class="form-control") }}
                {% for error in form.kind.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.price(class="form-control", placeholder='Price') }}
                {% for error in form.price.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.category_expenses.label }}
                {{ form.category_expenses(class="form-control") }}
                {% for error in form.category_expenses.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.category_incomes.label }}
                {{ form.category_incomes(class="form-control") }}
                {% for error in form.category_incomes.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col">
                        {{ form.day(class='form-control', placeholder='day (optional)') }}
                        {% for error in form.day.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
                    </div>
                    <div class="col">
                        {{ form.month(class='form-control', placeholder='month (optional)') }}
                        {% for error in form.month.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
                    </div>
                    <div class="col">
                        {{ form.year(class='form-control', placeholder='year (optional)') }}
                        {% for error in form.year.errors %}
                            <div class="invalid-feedback d-block">{{ error }}</div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.note(class="form-control", placeholder='Note (optional)', maxlength="32") }}
            </div>
            {{ form.submit(class="dark-button w-100") }}
        </form>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        function exchange() {
            let e = document.getElementById('kind');
            let exp = document.getElementById('category_expenses');
            let inc = document.getElementById('category_incomes');
            if (e.value === '0') {
                console.log(e.value);
                inc.style = 'border: 2px solid rgba(175,1,5,0.77)';
                exp.style = 'border: 2px solid rgba(41,175,25,0.77)';
            } else {
                console.log(e.value);
                exp.style = 'border: 2px solid rgba(175,1,5,0.77)';
                inc.style = 'border: 2px solid rgba(41,175,25,0.77)';
            }
        }
        exchange();
    </script>
{% endblock %}

app/templates/graph_categories_bar.html
{% extends 'base.html' %}


{% block app_content %}
    <div class="d-flex" style="background-color: #FFFFFF;">
        <canvas id="graph_bars"></canvas>
    </div>
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script>
        let cat = {{ cat|safe }};
        let price = {{ prices|safe }};
        let bar = document.getElementById('graph_bars').getContext('2d');
        new Chart(bar, {
            type: 'bar',
            data: {
                labels: cat,
                datasets: [{
                    label: 'Category',
                    data: price,
                    fill: false,
                    backgroundColor: "rgba(255,82,2, 0.8)",
                    borderColor: "rgba(255,5,7,0.8)",
                    borderWidth: 2,
                    hoverBackgroundColor: "rgba(255,82,2,1)",
                    hoverBorderColor: "rgba(255,5,7,1)",
                    lineTension: 0.1
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: "black"
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: "black",
                            beginAtZero: true
                        },
                        scaleLabel: {
                            display: true,
                            labelString: 'Price'
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: "black"
                        }
                    }]
                },
                title: {
                    display: true,
                    text: 'Costs by category'
                }
            }
        });
    </script>
{% endblock %}

app/templates/graph_category_per_day.html
{% extends 'base.html' %}


{% block app_content %}
    <canvas id="graph_category"></canvas>
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script>
        let days = {{ days|safe }};
        let prices = {{ prices|safe }};
        let category = '{{ category|safe }}';
        let chart = document.getElementById('graph_category').getContext('2d');
        new Chart(chart, {
            type: 'bar',
            data: {
                labels: days,
                datasets: [{
                    label: category,
                    data: prices,
                    fill: false,
                    backgroundColor: "rgba(168,0,255, 0.7)",
                    borderColor: "rgba(168,0,255,0.8)",
                    borderWidth: 2,
                    hoverBackgroundColor: "rgba(168,0,255,1)",
                    hoverBorderColor: "rgba(168,0,255,1)",
                    lineTension: 0.1
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: "black"
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: "black",
                            beginAtZero: true
                        },
                        scaleLabel: {
                            display: true,
                            labelString: 'Price'
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: "black"
                        },
                        scaleLabel: {
                            display: true,
                            labelString: 'Days'
                        }
                    }]
                },
                title: {
                    display: true,
                    text: 'Costs by category per day'
                }
            }
        })
    </script>
{% endblock %}

app/templates/graph_month_line.html
{% extends 'base.html' %}


{% block app_content %}
    <canvas id="graph_line"></canvas>
{% endblock %}


{% block scripts %}
    {{ super() }}
    <script>
        let month = {{ month|safe }};
        let price = {{ prices|safe }};
        let line = document.getElementById('graph_line').getContext('2d');
        new Chart(line, {
            type: 'line',
            data: {
                labels: month,
                datasets: [{
                    label: 'Expense',
                    data: price,
                    fill: false,
                    borderColor: "#130bb0",
                    lineTension: 0.1
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: 'black'
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: 'black',
                            beginAtZero:true
                        },
                        scaleLabel: {
                            display: true,
                            labelString: 'Price'
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: 'black'
                        }
                    }]
                },
                title: {
                    display: true,
                    text: 'Expenses per year'
                }
            }
        });
    </script>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}


{% block app_content %}
    <div class="d-flex justify-content-between">
        <div class="d-flex">
            <a href="{{ url_for('main.index', month=month-1, year=year) }}" class="btn-lg">&lt;</a>
            <h2>{{ date[0] }} {{ date[1] }}</h2>
            <a href="{{ url_for('main.index', month=month+1, year=year) }}" class="btn-lg">&gt;</a>
        </div>
        <a href="{{ url_for('card.create') }}"><button class="light-button">Add card</button></a>
    </div>
    <div class="d-flex my-3">
        <div class="flex-column">
            <a href="{{ prev_url }}">
                <button class="paginate-button" type="button" {% if prev_url is none %}disabled{% endif %}>
                    ❮
                </button>
            </a>
        </div>
        <div class="flex-column flex-grow-1">
            <table class="table my-0" style="background-color: #ffffff">
                {% for card in cards.items %}
                    {% include '_card.html' %}
                {% endfor %}
                <td><span class="index-card__total">Total</span></td>
                <td></td>
                {% if total < 0 %}
                    <td><span class="index-card__total f-right" style="color: #eb0000;">{{ total }} {{ currency }} </span></td>
                {% else %}
                    <td><span class="index-card__total f-right" style="color: #00af00;">+{{ total }} {{ currency }}</span></td>
                {% endif %}
            </table>
        </div>
        <div class="flex-column">
            <a href="{{ next_url }}">
                <button class="paginate-button" type="button" {% if next_url is none %}disabled{% endif %}>
                    ❯
                </button>
            </a>
        </div>
    </div>
    <div class="d-flex">
        <div class="flex-column flex-grow-1 bg-white mr-2">
            <p class="p-2 my-0">Top-5 expensive categories in {{ date[0] }} {{ date[1] }}</p>
            <table class="table">
            {% for percent in percents %}
                <tr>
                    <td class="percent"><span>{{ percent[0] }}</span></td>
                    <td class="percent"><span>{{ percent[1] }}</span></td>
                </tr>
            {% endfor %}
            </table>
        </div>
        <div class="flex-column flex-grow-1 bg-white ml-2" style="max-width: 550px;">
            <p class="p-2 my-0   border-bottom">Costs per {{ date[0] }} {{ date[1] }}</p>
            <canvas id="pieAllCategories"></canvas>
{#            <div style="width: 550px;">#}

{#            </div>#}
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        let categories = {{ categories|safe }};
        let prices = {{ prices|safe }}
        new Chart(document.getElementById("pieAllCategories").getContext('2d'), {
            type: 'pie',
            data: {
                labels: categories,
                datasets: [{
                    backgroundColor: {{ bg_colors|safe }},
                    data: prices,
                }]
            },
            options: {
                legend: {
                    display: true,
                    position: 'left'
                }
            }
        });
        $.ajax();
    </script>
{% endblock %}

app/templates/register.html
{% extends 'base.html' %}


{% block app_content %}
    <div class="d-flex justify-content-center">
        <form action="" method="post" class="style-form shadow p-3">
            {{ form.hidden_tag() }}
            <h2>Sign up</h2>
            <div class="form-group">
                {{ form.username(class='form-control', placeholder='Username') }}
                {% for error in form.username.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.email(class='form-control', placeholder='Email') }}
                {% for error in form.email.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.password(class='form-control', placeholder='Password') }}
                {% for error in form.password.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
                <small>Password must be 8-25 characters</small>
            </div>
            <div class="form-group">
                {{ form.password2(class='form-control', placeholder='Repeat password') }}
                {% for error in form.password2.errors %}
                    <div class="invalid-feedback d-block">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="d-flex justify-content-center">
                {{ form.submit(class='dark-button') }}
            </div>
        </form>
    </div>
    <div class="d-flex justify-content-center" style="margin-top: 30px;">
        <div class="d-flex flex-column">
            If you have already registered
            <a href="{{ url_for('auth.login') }}"><button class="light-button w-100">Sign in</button></a>
        </div>
    </div>
{% endblock %}

app/templates/reset_password.html
{% extends 'base.html' %}


{% block app_content %}
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.password.label }}<br>
            {{ form.password() }}<br>
            {% for error in form.password.errors %}
                <span style="color: red">{{ error }}</span>
            {% endfor %}
        </p>
        <p>
            {{ form.password2.label }}<br>
            {{ form.password2() }}<br>
            {% for error in form.password2.errors %}
                <span style="color: red">{{ error }}</span>
            {% endfor %}
        </p>
        {{ form.submit() }}
    </form>
{% endblock %}

app/templates/reset_password_request.html
{% extends 'base.html' %}


{% block app_content %}
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email() }}<br>
            {% for error in form.email.errors %}
                <span style="color: red;">{{ error }}</span>
            {% endfor %}
        </p>
        {{ form.submit() }}
    </form>
{% endblock %}

app/templates/statistics.html
{% extends 'base.html' %}


{% block app_content %}
    <div class="d-flex flex-column">
        <div class="d-flex flex-row">
            <div class="flex-column flex-grow-1 bg-white mr-2">
                <h3 class="p-2 border-bottom">{{ category }}</h3>
                <canvas id="chartBar"></canvas>
            </div>
            <div class="flex-column flex-grow-1 bg-white ml-2">
{#            <a href="{{ url_for('main.describe', category=category, year=year, month=month-1) }}">LEFT</a>#}
                <h3 class="p-2 border-bottom">{{ date[0] }} {{ date[1] }}</h3>
{#            <a href="{{ url_for('main.describe', category=category, year=year, month=month+1) }}">RIGHT</a>#}
                <canvas id="chartPie"></canvas>
            </div>
        </div>
        <div class="flex-column bg-white mt-3">
            <h3 class="p-2 border-bottom">{{ date[0] }} {{ date[1] }}</h3>
            <canvas id="chartLine"></canvas>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script>
        let months = {{ months|safe }};
        let prices = {{ prices_months|safe }};
        let bar = document.getElementById('chartBar').getContext('2d');
        new Chart(bar, {
            type: 'horizontalBar',
            data: {
                labels: months,
                datasets: [{
                    label: '{{ category }}',
                    data: prices,
                    fill: false,
                    backgroundColor: 'rgba(42,39,255,0.79)',
                    borderColor: 'rgba(42,39,255,0.79)',
                    borderWidth: 2,
                    hoverBackgroundColor: 'rgba(42,39,255,0.79)',
                    hoverBorderColor: 'rgba(42,39,255,0.79)',
                    lineTension: 0.1
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: "black"
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: "black"
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: "black",
                            beginAtZero: true
                        }
                    }]
                }
            }
        });

        let categories = {{ categories|safe }};
        let prices_cat = {{ prices_category|safe }};
        let pie = document.getElementById('chartPie').getContext('2d');
        new Chart(pie, {
            type: 'pie',
            data: {
                labels: categories,
                datasets: [{
                    data: prices_cat,
                    backgroundColor: ['rgba(42,39,255,0.79)'],
                }]
            },
            options: {
                legend: {
                    display: true,
                    position: 'left'
                }
            }
        });

        let days = {{ days|safe }};
        let prices_days = {{ prices_days|safe }};
        let line = document.getElementById('chartLine').getContext('2d');
        new Chart(line, {
            type: 'line',
            data: {
                labels: days,
                datasets: [{
                    label: '{{ category }}',
                    data: prices_days,
                    borderColor: 'rgba(42,39,255,0.79)',
                    backgroundColor: 'rgba(42,39,255,0.69)'
                }]
            },
            options: {
                legend: {
                    labels: {
                        fontColor: 'black'
                    }
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            fontColor: 'black',
                            beginAtZero: true
                        }
                    }],
                    xAxes: [{
                        ticks: {
                            fontColor: 'black'
                        }
                    }]
                }
            }
        })
    </script>
{% endblock %}

app/templates/table.html
{% extends 'base.html' %}


{% block app_content %}
    <table class="table table-bordered">
        <tr>
            <th scope="col">Category</th>
            <th scope="col">Price</th>
            <th scope="col">Year</th>
            <th scope="col">Month</th>
            <th scope="col">Day</th>
        </tr>
        {% for card in cards %}
            <tr>
                <td>{{ card.category }}</td>
                <td>{{ card.price }}</td>
                <td>{{ card.year }}</td>
                <td>{{ card.month }}</td>
                <td>{{ card.day }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}